### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by imbeard** [marcofacheris/npmit#1]
I tried your builder but it's failing at building

here's the log
14 verbose stack Error: npmit@1.2.0 build: `npm run build:js -s && npm run build:sass -s && npm run clean -s && echo 'Build succeded.'`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/andre/.nvm/versions/node/v5.11.1/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/andre/.nvm/versions/node/v5.11.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by marcofacheris** [comment]
Hi,

i just tried the latest build with a fresh install, and everything works fine. I'm using the latest version of Node (which at the time of writing is 6.2.0).
